import type { DemoRoleDefinition } from "../types";
import { at } from "../time";

export function evalrunnerRole(now = new Date()): DemoRoleDefinition {
  const tasks = [
    {
      title: "Trigger: View-Wechsel 1",
      priority: "low",
      dueDate: null,
      listName: "Eval",
      tags: ["trigger"],
      estimatedMinutes: 5,
    },
    {
      title: "Trigger: View-Wechsel 2",
      priority: "low",
      dueDate: null,
      listName: "Eval",
      tags: ["trigger"],
      estimatedMinutes: 5,
    },
    {
      title: "Erinnerungs-Aufgabe A",
      priority: "medium",
      dueDate: at(now, 0, 12, 0),
      reminderAt: at(now, 0, 11, 0),
      listName: "Eval",
      tags: ["erinnerung"],
      estimatedMinutes: 15,
    },
    {
      title: "Erinnerungs-Aufgabe B",
      priority: "medium",
      dueDate: at(now, 1, 12, 0),
      reminderAt: at(now, 1, 11, 0),
      listName: "Eval",
      tags: ["erinnerung"],
      estimatedMinutes: 15,
    },
    {
      title: "Erinnerungs-Aufgabe C",
      priority: "medium",
      dueDate: at(now, 2, 12, 0),
      reminderAt: at(now, 2, 11, 0),
      listName: "Eval",
      tags: ["erinnerung"],
      estimatedMinutes: 15,
    },
    {
      title: "Konflikt-Block 1",
      priority: "high",
      dueDate: at(now, 0, 10, 0),
      listName: "Eval",
      tags: ["konflikt"],
      estimatedMinutes: 120,
    },
    {
      title: "Konflikt-Block 2",
      priority: "high",
      dueDate: at(now, 0, 10, 0),
      listName: "Eval",
      tags: ["konflikt"],
      estimatedMinutes: 90,
    },
    {
      title: "Fokus: Wichtige Aufgabe",
      priority: "high",
      dueDate: at(now, 0, 9, 0),
      listName: "Eval",
      tags: ["fokus"],
      estimatedMinutes: 45,
    },
    {
      title: "Export-Check",
      priority: "medium",
      dueDate: at(now, 0, 17, 0),
      listName: "Eval",
      tags: ["export"],
      estimatedMinutes: 10,
    },
    {
      title: "Reset-Check",
      priority: "medium",
      dueDate: at(now, 0, 17, 30),
      listName: "Eval",
      tags: ["reset"],
      estimatedMinutes: 10,
    },
    // more varied surface area (keeps eval role demanding)
    {
      title: "Ansichten: Kurz hin und her (A)",
      priority: "low",
      dueDate: null,
      listName: "Eval",
      tags: ["trigger"],
      estimatedMinutes: 5,
    },
    {
      title: "Ansichten: Kurz hin und her (B)",
      priority: "low",
      dueDate: null,
      listName: "Eval",
      tags: ["trigger"],
      estimatedMinutes: 5,
    },
    {
      title: "Backlog: 3 Mini-Aufgaben bündeln",
      priority: "medium",
      dueDate: null,
      listName: "Eval",
      tags: ["cleanup"],
      estimatedMinutes: 15,
    },
    {
      title: "Kalender: Freien Slot auswählen",
      priority: "medium",
      dueDate: at(now, 0, 14, 0),
      listName: "Eval",
      tags: ["planning"],
      estimatedMinutes: 10,
    },
    {
      title: "Erinnerung: zweite Bestätigung",
      priority: "high",
      dueDate: at(now, 0, 18, 0),
      reminderAt: at(now, 0, 17, 45),
      listName: "Eval",
      tags: ["erinnerung"],
      estimatedMinutes: 10,
    },
    {
      title: "Überlast: Heute zu viel vornehmen",
      priority: "high",
      dueDate: at(now, 0, 16, 0),
      listName: "Eval",
      tags: ["focus"],
      estimatedMinutes: 180,
    },
    {
      title: "Überlast: noch ein Block (absichtlich)",
      priority: "high",
      dueDate: at(now, 0, 16, 0),
      listName: "Eval",
      tags: ["konflikt"],
      estimatedMinutes: 120,
    },
  ] as const;

  return {
    key: "evalrunner",
    label: "Eval-Runner",
    description: "Kleines, reproduzierbares Set für Suggestion-Lifecycle, Konflikte, Export & Reset.",
    tasks: [...tasks],
    // view_preference needs ≥4 hits to one VIEW_TARGETS route at intervention level 2 (threshold 4).
    viewEvents: [
      { from: "/heute", to: "/kalender" },
      { from: "/kalender", to: "/heute" },
      { from: "/heute", to: "/kalender" },
      { from: "/kalender", to: "/heute" },
      { from: "/heute", to: "/kalender" },
      { from: "/heute", to: "/kalender" },
    ],
    preferences: [
      { key: "adaptive.enabled", value: true },
      { key: "adaptive.interventionLevel", value: 2 },
    ],
    evaluations: [
      { screen: "task_created", taskTitle: "Export-Check", metadata: { source: "demo" } },
      { screen: "task_created", taskTitle: "Konflikt-Block 1", metadata: { source: "demo" } },
      { screen: "/heute", taskTitle: "Fokus: Wichtige Aufgabe", metadata: { trigger: "demo" } },
    ],
    eventLogMetadata: { role: "evalrunner", taskCount: tasks.length },
  };
}

